// <auto-generated />
using System;
using CodeDeckAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeDeckAPI.Migrations
{
    [DbContext(typeof(CodeCardContext))]
    [Migration("20200917182647_ChallengeTitle")]
    partial class ChallengeTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeDeckAPI.Models.CodeCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAnswers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Challenge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("JavaAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JavaScriptAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PythonAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.ToTable("CodeCards");
                });

            modelBuilder.Entity("CodeDeckAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodeCardCardId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CodeCardCardId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeDeckAPI.Models.User", b =>
                {
                    b.HasOne("CodeDeckAPI.Models.CodeCard", null)
                        .WithMany("UserCard")
                        .HasForeignKey("CodeCardCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
